### ISSUE TITLE
Omdat juw content zo lullig is

### ISSUE THREAD

**Issue by Theo-denBlanken** [Spyrincho/wordpressstylesheet#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/Spyrincho/wordpressstylesheet/blob/master/functions.php

Feedback: zie je niet goed of jouw thema wel werkt[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"fecc7842ae0c71749514640cfbcd72f312a7fa46","path":"functions.php","reviewer":"Theo-denBlanken"}')

**Comment by Spyrincho** [comment]
Probleem is opgelost
